### ISSUE TITLE
Cannot install using Python 3.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pcao10/pydelicious#43]
```
What steps will reproduce the problem?
1. Download the package
2. Open terminal
3. Go to the directory where the file is placed and unzip it
4. Run "python setup.py install"

What is the expected output? What do you see instead?
Expected to install, however this is the current output:

daniel@dqo:pydelicious - [ruby-1.9.2 - (master) $ ]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import pydelicious
  File "/Users/daniel/Documents/lang/python/pydelicious/pydelicious/__init__.py", line 171
    raise DeliciousItemExistsError, params['url']
                                  ^
SyntaxError: invalid syntax

What version of the product are you using? On what operating system?
Python 3.2.3 (default, Apr 19 2012, 01:32:56) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin

Please provide any additional information below.

```

Original issue reported on code.google.com by `danie...@gmail.com` on 6 Jan 2013 at 3:53

**Comment by arpitakumarsingh** [comment]
That works.
